# mongos.conf

# for documentation of all options, see:
#   http://docs.mongodb.org/manual/reference/configuration-options/

# Where and how to store data.
#storage:
#  dbPath: /var/lib/mongodb
#  journal:
#    enabled: true
#  engine:
#  mmapv1:
#  wiredTiger:

# where to write logging data.
systemLog:
  destination: file
  logAppend: true
  path: /var/log/mongodb/mongos.log

# network interfaces
net:
  #port: 27017
  #bindIp: 127.0.0.1
  port: 27017
{% set iplist = ansible_facts['default_ipv4']['address'].split('.') %}
{% set ip = '10.' ~ iplist[1] ~ '.' ~ iplist[2] ~ '.' ~ iplist[3] %}
  bindIp: {{ ip }}
# <begin> enabling tls authentication using x.509 certificates
  tls:
    mode: requireTLS
# note: in certificateKeyFile must be
# both pem and key, e.g.:
#  cat mongo.pem >  mongo.pemkey
#  cat mongo.key >> mongo.pemkey
# see: https://jira.mongodb.org/browse/SERVER-10495
    certificateKeyFile: /etc/mongo.pemkey
# CA to check also client certificates
    CAFile: /etc/ca.pem
security:
  clusterAuthMode: x509
# <end> enabling tls authentication using x.509 certificates


# how the process runs
processManagement:
  timeZoneInfo: /usr/share/zoneinfo

#security:

#operationProfiling:

#replication:

#sharding:
sharding:
  configDB: ipapi-mongo-config/ipapi-mongo-config-1.{{ my_domain }}.net:27019,ipapi-mongo-config-2.{{ my_domain }}.net:27019,ipapi-mongo-config-3.{{ my_domain }}.net:27019

## Enterprise-Only Options:

#auditLog:

#snmp:
